# This file configures the analyzer, which statically analyzes Dart code
# to check for errors, warnings, and lints.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Example of customization:
    # allow print statements
    avoid_print: false

    # enforce consistent string quotes
#    prefer_single_quotes: true

formatter:
  # Set maximum line length before breaking lines
  page_width: 120

  # Preserve existing trailing commas where possible
  trailing_commas: preserve
