// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Gq_1VrFr4bp-BaoPW52HISjWtxYAFFU',
    appId: '1:305305642988:web:710658857463ac19df42c9',
    messagingSenderId: '305305642988',
    projectId: 'for-delete-c0d5f',
    authDomain: 'for-delete-c0d5f.firebaseapp.com',
    databaseURL: 'https://for-delete-c0d5f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'for-delete-c0d5f.appspot.com',
    measurementId: 'G-31VPQ2H99J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTnjM-flYLtea69ov0zQrlsuSHDA9GKxM',
    appId: '1:305305642988:android:a4f7119a5a802abfdf42c9',
    messagingSenderId: '305305642988',
    projectId: 'for-delete-c0d5f',
    databaseURL: 'https://for-delete-c0d5f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'for-delete-c0d5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdggdM_VPz8A1QX02BXQxaXLSNsIDZXYQ',
    appId: '1:305305642988:ios:41c46396f97796a1df42c9',
    messagingSenderId: '305305642988',
    projectId: 'for-delete-c0d5f',
    databaseURL: 'https://for-delete-c0d5f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'for-delete-c0d5f.appspot.com',
    iosBundleId: 'com.example.testRtd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWvn3DqvC_6cBR5i8mvQ2Fk-I_odEMTeg',
    appId: '1:305305642988:web:e6c02213f5d89137df42c9',
    messagingSenderId: '305305642988',
    projectId: 'for-delete-c0d5f',
    authDomain: 'for-delete-c0d5f.firebaseapp.com',
    databaseURL: 'https://for-delete-c0d5f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'for-delete-c0d5f.appspot.com',
    measurementId: 'G-53QQGJMDM1',
  );
}
